### ISSUE TITLE
Doorbell on Alexa

### ISSUE THREAD

**Issue by sim404** [sinricpro/non-sdk-issues#29]
Hi,
A question re the doorbell code please: I’ve been using the doorbell example based code for some months and it works fine. I have several Alexa devices inc show, show5 and dot. I have an Alexa routine against each device triggered by the doorbell press. Originally all the routines worked fine and simultaneously as intended. However, a few months or so ago they have become random in that not all of them work all of the time. My question (at last…) is, would this likely be an Alexa issue, or, could it be something to do with the sinricPro server code? If neither, views please on how I might fix it. Thanks.

**Comment by sivar2311** [comment]
Were the doorbells connected to WiFi at the time and were they also displayed as "online" in the dashboard? 
My guess is that the problem lies here.

**Comment by sim404** [comment]
I might have misunderstood what should be possible with this. I have one instance of doorbell on sinricPro (and it shows online on the dashboard). I have one esp32 running the doorbell code. I have four Alexa devices in the home and a separate Alexa routine for each triggered (or should be) by that same sinricPro  doorbell instance.  The whole thing is designed to make sure I hear the doorbell throughout the home. Maybe I’m stretching the thing too far? Thanks for your time on this.

**Comment by sim404** [comment]
And forgot to say. WiFi strong and everything connected.

**Comment by sivar2311** [comment]
Oh, then I misunderstood. Thank you for the clarification.
Please check if the "Do not disturb" function is enabled on the affected Alexa devices. This would prevent the doorbell function.
(I have activated this function e.g. on the Alexa in the children's room - so that the doorbell is not heard there every time).

**Comment by sim404** [comment]
Thanks for your response. Checked the do not disturb/s and all the devices have it ‘off’.  It’s a bit of a mystery to me at least but my money is on it being a problem after the  SinricP/AWS interface. Maybe AWS doesn’t like kicking off 4 routines simultaneously from a single trigger. A totally unscientific analysis! So thank you for looking at it, I’ll do a bit more at my end to try to pin it down a bit better. In the meantime I’ll close the issue. Cheers.

**Comment by sivar2311** [comment]
I have just tested it.
The normal doorbell function runs without any problems.

It looks like there have been a lot of changes in the routines on Alexa's side:
A doorbell as a trigger for a routine: the routine is not triggered.
A contact sensor: can no longer be selected as a trigger for a routine (which was possible before).

**Comment by sim404** [comment]
Crikey, are you saying that according to AWS spec my use of a routine should not be working at all?

**Comment by sivar2311** [comment]
I just tried it and share my observations....
Maybe it is also (again) country specific.
It has often happened that when Amazon changes something in the routines, suddenly something no longer works.
Here in Germany, Amazon has recently changed a lot of the routines (sounds as triggers). The settings for doorbells have also been completely changed.
I therefore do not think that it is a problem in the communication between the Alexa server and the SinricPro server, but is solely due to Alexa.

**Comment by sim404** [comment]
Thanks for spending time on it. Looks like I’ll have to look for a new doorbell scheme at some stage in the future….(in UK)
